apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-app
  template:
    metadata:
      labels:
        app: alpine-app
    spec:
      containers:
      - name: alpine-container
        image: alpine:latest
        command: ["ash", "-c", "sleep infinity"]


---

apiVersion: v1
kind: Service
metadata:
  name: alpine-service
spec:
  selector:
    app: alpine-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
